### PR TITLE
Added port option to run

### PR DESCRIPTION
**Pull request by itsjoniur**

### CODE REVIEW

**Comment by Kludex** [comment]
Maybe we'd want to refactor that thing... 🤔

**Comment by AhmadAmoori** [comment]
do u have any idea about it?

**Comment by AhmadAmoori** [comment]
> Maybe we'd want to refactor that thing... 🤔 

do u have any idea about it?

**Comment by Kludex** [comment]
Thanks for creating this PR @itsjoniur ! :)

I think we shouldn't aim to replace `uvicorn`. If more complex arguments are needed (even such as simple as port) then you should use `uvicorn` itself.

For the reason mentioned above, I'll close this. 🙏

**Pull request closed without merging**
